version: '3'
services:
  marieadb:
    image: mariadb:10.5.5
    container_name: mysql
    networks:
      default:
        ipv4_address: 10.5.0.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mysite_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - marieadb
    networks:
      default:
        ipv4_address: 10.5.0.6
    environment:
      # - MYSQL_USERNAME=admin
      # - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - 8080:80

networks:
  default: 
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/24